# Generated by Django 4.2.11 on 2024-04-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
