# Generated by Django 4.2.11 on 2024-04-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='autumn',
            field=models.CharField(blank=True, choices=[('', ''), ('1A', '1A')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='spring',
            field=models.CharField(blank=True, choices=[('', ''), ('1A', '1A')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='summer',
            field=models.CharField(blank=True, choices=[('', ''), ('1A', '1A')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='winter',
            field=models.CharField(blank=True, choices=[('', ''), ('1A', '1A')], max_length=2, null=True),
        ),
    ]
