# Generated by Django 4.2.11 on 2024-04-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0003_alter_levels_autumn_alter_levels_spring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='pereval',
            old_name='other_title',
            new_name='other_titles',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='images',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PerevalApp.pereval'),
        ),
    ]
