# Generated by Django 4.2.11 on 2024-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0004_images_rename_other_title_pereval_other_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.BinaryField(),
        ),
    ]
