# Generated by Django 4.2.11 on 2024-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0005_alter_images_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'в обработке'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='new', max_length=8),
        ),
    ]
