# Generated by Django 4.2.11 on 2024-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0006_pereval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='autumn',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('1Б', '2-Б'), ('1Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='spring',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('1Б', '2-Б'), ('1Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='summer',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('1Б', '2-Б'), ('1Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='winter',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('1Б', '2-Б'), ('1Б', '3-Б')], max_length=2, null=True),
        ),
    ]
