# Generated by Django 4.2.11 on 2024-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0007_alter_images_data_alter_levels_autumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='autumn',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('2Б', '2-Б'), ('3Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='spring',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('2Б', '2-Б'), ('3Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='summer',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('2Б', '2-Б'), ('3Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='winter',
            field=models.CharField(blank=True, choices=[('', ''), ('1А', '1-А'), ('2А', '2-А'), ('3А', '3-А'), ('1Б', '1-Б'), ('2Б', '2-Б'), ('3Б', '3-Б')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'новый'), ('pending', 'в обработке'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='new', max_length=8),
        ),
    ]
